name: Deploy master-upline-website changes to EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# permissions:
#   contents: read

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
  
# CHECKOUT THE PUSHED CODE TO THE RUNNER BY USING A PREDEFINED ACTION
    steps:
#       - name: Checkout the files
#         uses: actions/checkout@v2
    
# COMMITING CHANGES TO THE EC2 SERVER, IN ORDER TO DO THIS WE NEED TO ACCESS THE EC2 USING SSH AND PERFORM RSYNC FROM THE RUNNER
      - name: Deploy to EmasKiara-website EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MU_HOST_DNS }} # Public DNS record of the instance, it will look something like this ec2-xx-xxx-xxx-xxx.us-west-2.compute.amazonaws.com
          # port: ${{ secrets.LM_PORT }}
          username: ${{ secrets.MU_USERNAME }} # BY DEFAULT IS ubuntu
          key: ${{ secrets.MU_SSH_KEY }} # PRIVATE SSH key
          script_stop: true
          script: |
            cd /var/www/html
            git pull origin main
